package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/abn/coprctl/internal/detect"
)

// coprMakefileParams carries what detect learned about a template-spec
// project into the generated .copr/Makefile.
type coprMakefileParams struct {
	// SpecTemplate is the repo-relative template path, e.g. packaging/rpm/foo.spec.in.
	SpecTemplate string
	// SpecName is the rendered spec basename Copr consumes, e.g. foo.spec.
	SpecName string
	// PackageName is the RPM package name.
	PackageName string
	// SourceName is the tarball directory stem parsed from the template's
	// Source0 or %autosetup line, falling back to PackageName.
	SourceName string
	// HasCargo includes the cargo vendor step for an offline Rust build.
	HasCargo bool
	// RustVersion records the workspace rust-version for the maintainer.
	RustVersion string
	// Subst maps each @TOKEN@ placeholder in the template to its replacement.
	Subst []tokenSubst
}

// tokenSubst maps one template placeholder to the sed replacement expression.
// Known version tokens expand to shell variables computed in the recipe;
// anything else expands to a make variable of the same name, which the user
// passes on the make command line.
type tokenSubst struct {
	Token string
	Expr  string
	// MakeVar names the make variable to define when Expr references one.
	MakeVar string
}

var (
	reSpecToken  = regexp.MustCompile(`@([A-Za-z][A-Za-z0-9_]*?)@`)
	reAutosetup  = regexp.MustCompile(`(?m)^%autosetup\b.*?\-n\s+(\S+)`)
	reSourceBase = regexp.MustCompile(`(?m)^Source0?:\s*(\S+)`)
	reMacro      = regexp.MustCompile(`%\{[^}]*\}`)
	reArchiveExt = regexp.MustCompile(`\.(tar\.(gz|bz2|xz|zst)|tgz|zip)$`)
	// A versioned Source0 basename (foo-2.0.tgz) usually unpacks under the
	// default %{name}-%{version} directory, so the stem drops the trailing
	// version; the recipe re-appends the real one.
	reTrailingVersion = regexp.MustCompile(`-v?\d[\w.]*$`)
)

// renderCoprMakefile renders a make_srpm srpm target: it derives the version
// from the git tag, renders the template spec, packs the sources, vendors
// Rust dependencies when needed, and shells out to rpmbuild -bs with the
// result in $(outdir).
//
// Copr invokes this as `make -f <repo>/.copr/Makefile srpm outdir=...
// spec=...` from the cloned checkout, as root in a mock chroot with network
// access; the build of the resulting SRPM is offline. See the Copr user
// documentation, "Build Source Types". The scaffold renders SPEC_TEMPLATE
// instead of consuming $(spec): the template is the source of truth.
func renderCoprMakefile(p coprMakefileParams) string {
	var b strings.Builder
	b.WriteString("# Generated by `coprctl init`. Copr runs the `srpm` target as root\n")
	b.WriteString("# in a mock chroot with network access, then builds the resulting\n")
	b.WriteString("# SRPM offline, so anything the build needs (vendored crates, the\n")
	b.WriteString("# source tarball) must be packed here.\n")
	b.WriteString("#\n")
	b.WriteString("# VERSION defaults to the latest v-prefixed tag. When the release\n")
	b.WriteString("# version lives elsewhere (for example a Cargo.toml version field),\n")
	b.WriteString("# override it on the make command line: make srpm outdir=... VERSION=1.2.3\n")
	b.WriteString("# SOURCE_NAME was parsed from the template; verify it against the\n")
	b.WriteString("# spec's %autosetup directory before the first real build.\n")
	for _, s := range p.Subst {
		if s.MakeVar != "" {
			fmt.Fprintf(&b, "# @%s@ has no derivable value: pass %s=... to make.\n", s.MakeVar, s.MakeVar)
		}
	}
	if p.HasCargo {
		if p.RustVersion != "" {
			fmt.Fprintf(&b, "# Workspace rust-version detected as %s: keep the chroot cargo\n", p.RustVersion)
			b.WriteString("# BuildRequires in step with it.\n")
		}
		b.WriteString("# Vendoring needs a committed Cargo.lock (--locked) and the network\n")
		b.WriteString("# Copr provides at srpm time.\n")
	}
	fmt.Fprintf(&b, "SPEC_TEMPLATE := %s\n", p.SpecTemplate)
	fmt.Fprintf(&b, "SPEC_NAME     := %s\n", p.SpecName)
	fmt.Fprintf(&b, "PACKAGE       := %s\n", p.PackageName)
	fmt.Fprintf(&b, "SOURCE_NAME   := %s\n", p.SourceName)
	b.WriteString("\n")
	b.WriteString("# Repo-relative paths are anchored at the checkout top: Copr may run\n")
	b.WriteString("# this target from the package subdirectory, and git works from anywhere\n")
	b.WriteString("# inside the clone.\n")
	b.WriteString("REPO ?= $(shell git rev-parse --show-toplevel 2>/dev/null)\n")
	b.WriteString("\n")
	b.WriteString("# Tag v1.2.3 becomes version 1.2.3; v1.2.3-rc.1 becomes 1.2.3 with\n")
	b.WriteString("# a 0.rc.1 release. Override for test builds:\n")
	b.WriteString("#   make srpm outdir=/tmp/out VERSION=1.2.3-rc.1\n")
	b.WriteString("VERSION ?= $(shell git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')\n")
	b.WriteString("\n")
	b.WriteString("# The rpmbuild -bs call below passes dist %{nil}: the SRPM carries no\n")
	b.WriteString("# dist tag, and Copr re-evaluates %{?dist} per chroot at build time.\n")
	b.WriteString("\n")
	b.WriteString("srpm:\n")
	b.WriteString("\tset -eu; \\\n")
	b.WriteString("\t[ -n \"$(VERSION)\" ] || { echo \"VERSION is empty (no v-prefixed tag?); pass VERSION=x.y.z\" >&2; exit 1; }; \\\n")
	b.WriteString("\tfor tool in git tar rpmbuild; do command -v \"$$tool\" >/dev/null || { echo \"$$tool is missing from the srpm chroot; add 'dnf -y install ...' above\" >&2; exit 1; }; done; \\\n")
	b.WriteString("\tgit diff-index --quiet HEAD -- || echo \"warning: uncommitted changes are not in the SRPM\" >&2; \\\n")
	b.WriteString("\twork=$$(mktemp -d); trap 'rm -rf \"$$work\"' EXIT; \\\n")
	b.WriteString("\tmkdir -p \"$$work/SOURCES\" \"$$work/SPECS\" \"$(outdir)\"; \\\n")
	b.WriteString("\trpm_version=\"$(VERSION)\"; rpm_release='1%{?dist}'; \\\n")
	b.WriteString("\tcase \"$$rpm_version\" in \\\n")
	b.WriteString("\t*-*) pre=\"$${rpm_version#*-}\"; rpm_version=\"$${rpm_version%%-*}\"; \\\n")
	b.WriteString("\t\tpre=$$(printf '%s' \"$$pre\" | tr -c '[:alnum:].' '.'); \\\n")
	b.WriteString("\t\trpm_release=\"0.$${pre}%{?dist}\";; \\\n")
	b.WriteString("\tesac; \\\n")
	b.WriteString("\troot=\"$$work/$(SOURCE_NAME)-$$rpm_version\"; \\\n")
	b.WriteString("\tmkdir -p \"$$root\"; \\\n")
	b.WriteString("\tgit archive --format=tar HEAD | tar -x -C \"$$root\"; \\\n")
	if p.HasCargo {
		b.WriteString("\tcommand -v cargo >/dev/null || { echo \"cargo is missing from the srpm chroot; add 'dnf -y install cargo' above\" >&2; exit 1; }; \\\n")
		b.WriteString("\t(cd \"$$root\" && cargo vendor --locked --versioned-dirs vendor >/dev/null); \\\n")
		b.WriteString("\tmkdir -p \"$$root/.cargo\"; \\\n")
		b.WriteString("\tprintf '%s\\n' '[source.crates-io]' 'replace-with = \"vendored-sources\"' '' '[source.vendored-sources]' 'directory = \"vendor\"' > \"$$root/.cargo/config.toml\"; \\\n")
	}
	if len(p.Subst) == 0 {
		b.WriteString("\tcp \"$(REPO)/$(SPEC_TEMPLATE)\" \"$$work/SPECS/$(SPEC_NAME)\"; \\\n")
	} else {
		b.WriteString("\tsed")
		for _, s := range p.Subst {
			fmt.Fprintf(&b, " -e \"s|%s|%s|g\"", s.Token, s.Expr)
		}
		b.WriteString(" \\\n")
		b.WriteString("\t\t\"$(REPO)/$(SPEC_TEMPLATE)\" > \"$$work/SPECS/$(SPEC_NAME)\"; \\\n")
	}
	b.WriteString("\ttar -C \"$$work\" -czf \"$$work/SOURCES/$(SOURCE_NAME)-$$rpm_version.tar.gz\" \"$(SOURCE_NAME)-$$rpm_version\"; \\\n")
	b.WriteString("\trpmbuild --define \"_topdir $$work\" --define \"dist %{nil}\" -bs \"$$work/SPECS/$(SPEC_NAME)\"; \\\n")
	b.WriteString("\tcp \"$$work\"/SRPMS/*.src.rpm \"$(outdir)/\"\n")
	return b.String()
}

// makefileParams derives the scaffold variables from the first template spec
// in the detection result. It reports false when the project needs no
// .copr/Makefile (no template specs, or one already exists).
func makefileParams(res *detect.Result) (coprMakefileParams, bool) {
	if res.HasCoprMake {
		return coprMakefileParams{}, false
	}
	for _, s := range res.Specs {
		if !s.Template {
			continue
		}
		mp := coprMakefileParams{
			SpecTemplate: filepath.ToSlash(s.Path),
			SpecName:     strings.TrimSuffix(filepath.Base(s.Path), ".in"),
			PackageName:  s.Name,
			SourceName:   s.Name,
			HasCargo:     res.HasCargo,
			RustVersion:  res.RustVersion,
		}
		if data, err := os.ReadFile(filepath.Join(res.RepoDir, filepath.FromSlash(s.Path))); err == nil {
			text := string(data)
			mp.Subst = templateSubst(text)
			if stem := sourceStem(text, s.Name); stem != "" {
				mp.SourceName = stem
			}
		}
		return mp, true
	}
	return coprMakefileParams{}, false
}

// templateSubst maps every @TOKEN@ placeholder in the template to its sed
// replacement. The version and release tokens expand to shell variables the
// recipe computes; anything else becomes a make variable of the same name.
func templateSubst(text string) []tokenSubst {
	var out []tokenSubst
	seen := map[string]bool{}
	for _, m := range reSpecToken.FindAllStringSubmatch(text, -1) {
		token, body := m[0], m[1]
		if seen[token] {
			continue
		}
		seen[token] = true
		switch body {
		case "RPM_VERSION":
			out = append(out, tokenSubst{Token: token, Expr: "$${rpm_version}"})
		case "RPM_RELEASE":
			out = append(out, tokenSubst{Token: token, Expr: "$${rpm_release}"})
		default:
			out = append(out, tokenSubst{Token: token, Expr: fmt.Sprintf("$(%s)", body), MakeVar: body})
		}
	}
	return out
}

// sourceStem derives the tarball directory stem from the template's
// %autosetup -n directory or Source0 basename, stripping %{macros} and
// archive extensions. It falls back to the package name when unparseable.
func sourceStem(text, fallback string) string {
	if m := reAutosetup.FindStringSubmatch(text); m != nil {
		if stem := stripMacros(m[1]); stem != "" {
			return stem
		}
	}
	if m := reSourceBase.FindStringSubmatch(text); m != nil {
		base := m[1]
		if i := strings.LastIndex(base, "/"); i >= 0 {
			base = base[i+1:]
		}
		base = reArchiveExt.ReplaceAllString(base, "")
		base = reTrailingVersion.ReplaceAllString(stripMacros(base), "")
		if stem := strings.Trim(base, "-_."); stem != "" {
			return stem
		}
	}
	return fallback
}

// stripMacros removes %{...} macro references and any dangling separators.
func stripMacros(s string) string {
	s = reMacro.ReplaceAllString(s, "")
	return strings.Trim(s, "-_.")
}
